Usage message and fail silently if the file never existed
1) git-first --help works
2) git-first xyzzy exits with failure
(This makes it easier to use in scripts.)

diff --git a/git-first b/git-first
--- a/git-first
+++ b/git-first
@@ -1,3 +1,13 @@
 #!/bin/bash
 
-git log --oneline master -- $1 | tail -1 | cut -f1 -d' ' # SHA1 of first commit with file $1
+die() { echo "$@" >&2; exit 1; }
+usage="usage:$0 [--help] <filename>"
+
+[[ $1 == --help ]] && die $usage
+
+sha1=$(git log --oneline master -- $1 | tail -1 | cut -f1 -d' ') # SHA1 of first commit with file $1
+if [ "${sha1}" ]; then
+  echo $sha1
+else
+  false # fail silently if there is none
+fi
